server:
  port: 8080
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  

spring:
  application:
    name: msj-api-gateway
  cloud:
    gateway:
      routes:
      - id: cadastrosEssenciais
        uri: lb://MSJ-CADASTROS-ESSENCIAIS
        predicates:
        - Path=/cidades/**,/estados/**
      - id: clientes
        uri: lb://MSJ-CLIENTES
        predicates:
        - Path=/clientes/**