server:
  port: ${PORT:0}
 
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  

spring:
  application:
    name: msj-clientes
  jpa:
    database: MYSQL
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3307/rf-modulo-clientes?createDatabaseIfNotExist=true&useSSL=false
    username: renanfretta
    password: Ren@nFretta1986